export default [
  {
    _id: '5c8ea07c78e3d8d723f226e1',
    index: 0,
    guid: '43535adf-66ac-43e5-810e-4663ed3463b2',
    featuredImage: 'http://placehold.it/640x640',
    pictures: [
      'http://placehold.it/32x32',
      'http://placehold.it/32x32',
      'http://placehold.it/32x32',
    ],
    name: 'Lamb Woodard',
    region: 'Minnesota',
    company: 'WEBIOTIC',
    email: 'lambwoodard@webiotic.com',
    phone: '+1 (966) 556-3242',
    address: '981 Huron Street, Cotopaxi, Kentucky, 7417',
    about:
      'Consectetur est elit aliqua nostrud magna laboris mollit veniam velit magna pariatur aliqua irure ipsum. Excepteur minim adipisicing minim magna et ad. Veniam enim ea deserunt nisi fugiat sit deserunt labore tempor. Lorem aliquip quis labore pariatur occaecat pariatur. Adipisicing nulla velit do in magna tempor. Incididunt consectetur consectetur ullamco non veniam veniam. Et laborum pariatur sunt consectetur sint ut pariatur.\r\n',
    useful:
      'Commodo sit excepteur ipsum culpa ullamco non consectetur in aliqua reprehenderit laborum proident enim. Occaecat quis deserunt in eu reprehenderit. Nisi ullamco mollit non ea labore officia duis amet id cupidatat ea ipsum elit eu.\r\n',
    registered: '2017-03-21T10:50:40 -00:00',
    latitude: -34.435059,
    longitude: -71.56521,
    wines: [
      {
        name: 'aliqua deserunt irure sint',
        year: 1972,
        color: 'red',
        type: 'excepteur eiusmod',
        price: 8,
      },
      {
        name: 'id exercitation laboris dolor',
        year: 1982,
        color: 'white',
        type: 'deserunt qui',
        price: 11,
      },
      {
        name: 'magna consectetur ullamco proident',
        year: 1983,
        color: 'red',
        type: 'dolore ea',
        price: 8,
      },
      {
        name: 'cillum eu est cillum',
        year: 2007,
        color: 'red',
        type: 'laborum cupidatat',
        price: 5,
      },
      {
        name: 'eiusmod elit ex sit',
        year: 1957,
        color: 'white',
        type: 'consectetur consectetur',
        price: 8,
      },
      {
        name: 'enim esse nulla cupidatat',
        year: 1971,
        color: 'red',
        type: 'veniam culpa',
        price: 8,
      },
    ],
    activities: [
      {
        title: 'pariatur reprehenderit',
        type: 'tour',
        length: 1800000,
        size: 4,
        details:
          'Mollit tempor fugiat dolor cupidatat laborum duis. Dolore quis mollit ullamco exercitation velit deserunt mollit dolor enim sint. Cillum ipsum nulla id veniam eiusmod incididunt exercitation culpa fugiat. Quis quis amet qui tempor ex enim mollit amet occaecat sint. Irure ad officia duis officia nisi nostrud sint.\r\n',
        price: 160,
      },
    ],
  },
  {
    _id: '5c8ea07c565616225a2003b7',
    index: 1,
    guid: 'b78c9c66-991b-441f-b3bd-352ddec2096c',
    featuredImage: 'http://placehold.it/640x640',
    pictures: [
      'http://placehold.it/32x32',
      'http://placehold.it/32x32',
      'http://placehold.it/32x32',
    ],
    name: 'Moon Mcclure',
    region: 'Palau',
    company: 'ANACHO',
    email: 'moonmcclure@anacho.com',
    phone: '+1 (805) 489-2738',
    address: '793 Rockaway Parkway, Holcombe, Alaska, 7790',
    about:
      'Nostrud ex ipsum voluptate minim ut Lorem ea consequat esse Lorem aliquip deserunt. Id culpa voluptate nostrud irure non eiusmod cillum. Nisi eiusmod officia adipisicing ut. Dolor ex aute consectetur aute Lorem quis dolor do consequat. Est sit cillum nulla ea minim exercitation incididunt id nulla adipisicing sit sunt elit deserunt.\r\n',
    useful:
      'Ad pariatur ipsum dolor fugiat fugiat commodo exercitation dolor amet anim irure voluptate ex. Dolor aute magna elit nulla magna esse cupidatat consequat ea commodo fugiat. Nostrud eiusmod ipsum incididunt in est anim et proident anim.\r\n',
    registered: '2017-11-19T12:11:04 -00:00',
    latitude: 54.00809,
    longitude: 122.747182,
    wines: [
      {
        name: 'commodo fugiat duis dolore',
        year: 1982,
        color: 'red',
        type: 'laborum dolor',
        price: 7,
      },
      {
        name: 'amet irure duis adipisicing',
        year: 1993,
        color: 'red',
        type: 'nisi mollit',
        price: 18,
      },
      {
        name: 'et cillum laborum do',
        year: 1952,
        color: 'white',
        type: 'ullamco qui',
        price: 8,
      },
      {
        name: 'incididunt ullamco Lorem enim',
        year: 2017,
        color: 'red',
        type: 'non dolore',
        price: 20,
      },
      {
        name: 'dolore ut ex sunt',
        year: 1960,
        color: 'red',
        type: 'id enim',
        price: 8,
      },
    ],
    activities: [
      {
        title: 'id dolore',
        type: 'tasting',
        length: 1800000,
        size: 10,
        details:
          'Labore incididunt consectetur labore amet excepteur elit mollit dolore consequat veniam ullamco elit enim. Enim qui eu laboris irure laborum cillum consequat enim reprehenderit. Sint sit occaecat pariatur officia voluptate aute in minim voluptate tempor esse mollit. Duis duis qui dolore anim voluptate. Laboris proident commodo mollit officia laboris reprehenderit quis. Et pariatur id nulla magna anim aliqua.\r\n',
        price: 133,
      },
    ],
  },
  {
    _id: '5c8ea07cf9373fbc7a60541c',
    index: 2,
    guid: '443e7f8d-66be-4602-b2d1-95cb55966c64',
    featuredImage: 'http://placehold.it/640x640',
    pictures: [
      'http://placehold.it/32x32',
      'http://placehold.it/32x32',
      'http://placehold.it/32x32',
    ],
    name: 'Bates Maldonado',
    region: 'Maine',
    company: 'MEDICROIX',
    email: 'batesmaldonado@medicroix.com',
    phone: '+1 (855) 531-2989',
    address: '222 Vista Place, Benson, Puerto Rico, 6538',
    about:
      'Lorem dolor ea et ipsum ut magna Lorem quis sunt irure do. Veniam dolor ipsum esse velit officia nostrud ut nisi pariatur velit quis mollit deserunt velit. Officia anim irure quis labore ut consectetur eiusmod esse quis qui incididunt et. Aliquip sint magna ullamco fugiat enim laborum minim.\r\n',
    useful:
      'Incididunt nulla adipisicing exercitation officia aliqua occaecat velit sint. Excepteur laborum eu voluptate exercitation aute eiusmod id excepteur mollit nulla sint amet. Eu labore aliqua pariatur nulla culpa velit nisi ullamco sint pariatur reprehenderit sunt ex commodo. Et ut laborum tempor proident. In irure nisi magna voluptate deserunt. Lorem nulla magna amet enim est adipisicing qui ut enim reprehenderit sit.\r\n',
    registered: '2018-01-25T04:38:54 -00:00',
    latitude: -34.435059,
    longitude: -73.56521,
    wines: [
      {
        name: 'ut et consequat aliqua',
        year: 1953,
        color: 'white',
        type: 'excepteur minim',
        price: 15,
      },
      {
        name: 'qui est fugiat veniam',
        year: 2011,
        color: 'red',
        type: 'amet sunt',
        price: 20,
      },
      {
        name: 'nisi officia proident ex',
        year: 1992,
        color: 'red',
        type: 'excepteur laboris',
        price: 12,
      },
      {
        name: 'sit et in voluptate',
        year: 2003,
        color: 'white',
        type: 'nisi incididunt',
        price: 8,
      },
      {
        name: 'reprehenderit ex aute consequat',
        year: 1992,
        color: 'white',
        type: 'dolor eu',
        price: 8,
      },
      {
        name: 'adipisicing velit commodo sint',
        year: 1994,
        color: 'red',
        type: 'amet labore',
        price: 10,
      },
      {
        name: 'duis dolor enim in',
        year: 1952,
        color: 'red',
        type: 'anim officia',
        price: 8,
      },
    ],
    activities: [
      {
        title: 'minim enim',
        type: 'tasting',
        length: 1800000,
        size: 5,
        details:
          'Officia et sunt sit ullamco nulla ea occaecat adipisicing pariatur nisi sit anim minim amet. Ullamco aute aute proident velit enim do. In laborum elit laboris dolore adipisicing eiusmod duis.\r\n',
        price: 80,
      },
    ],
  },
  {
    _id: '5c8ea07c52640facf26e42a9',
    index: 3,
    guid: '5671746e-ed7d-4454-804b-407196a1d2fb',
    featuredImage: 'http://placehold.it/640x640',
    pictures: ['http://placehold.it/32x32'],
    name: 'Dionne Flowers',
    region: 'Northern Mariana Islands',
    company: 'ZEROLOGY',
    email: 'dionneflowers@zerology.com',
    phone: '+1 (980) 546-3790',
    address: '232 Carlton Avenue, Golconda, Arkansas, 3705',
    about:
      'Ipsum dolore in Lorem ipsum pariatur. Dolor cillum duis quis ex eiusmod reprehenderit fugiat laborum sint ex fugiat velit dolore magna. Enim in aliqua est nostrud mollit et aliqua reprehenderit ea exercitation sint. Qui ipsum fugiat quis dolor et aute nisi eu enim sunt irure. Officia ullamco Lorem sunt aliquip magna magna.\r\n',
    useful:
      'Adipisicing ipsum culpa mollit ad minim sunt nostrud quis. Qui aute mollit non duis. Quis qui ut elit officia ut laboris ullamco voluptate sit ad. Ipsum ad excepteur nostrud nulla laborum. Adipisicing aliqua non laboris enim aliquip ipsum anim deserunt consectetur. Proident non occaecat aute occaecat culpa ullamco ipsum eu ea. Nisi aute fugiat quis ea eu anim deserunt dolore ea dolor cupidatat exercitation aliqua.\r\n',
    registered: '2018-05-08T09:32:28 -01:00',
    latitude: -32.435059,
    longitude: -74.56521,
    wines: [
      {
        name: 'culpa officia ex mollit',
        year: 1968,
        color: 'white',
        type: 'aliquip reprehenderit',
        price: 8,
      },
      {
        name: 'exercitation aliqua ullamco et',
        year: 1970,
        color: 'red',
        type: 'elit ipsum',
        price: 12,
      },
      {
        name: 'aliquip est fugiat aliqua',
        year: 1992,
        color: 'red',
        type: 'do sunt',
        price: 8,
      },
      {
        name: 'consectetur pariatur tempor ex',
        year: 2002,
        color: 'white',
        type: 'ipsum dolor',
        price: 15,
      },
      {
        name: 'eiusmod id non commodo',
        year: 2004,
        color: 'red',
        type: 'nostrud sit',
        price: 8,
      },
    ],
    activities: [
      {
        title: 'duis aute',
        type: 'tasting',
        length: 1800000,
        size: 12,
        details:
          'Quis adipisicing duis voluptate fugiat laboris commodo aliquip elit. Magna nulla enim pariatur commodo officia ullamco eiusmod ipsum. Duis reprehenderit culpa labore nostrud tempor cupidatat nulla amet et veniam deserunt veniam nulla reprehenderit. Ex id elit nostrud veniam aute mollit incididunt adipisicing mollit ut consectetur. Voluptate aliquip ullamco exercitation sint adipisicing.\r\n',
        price: 110,
      },
    ],
  },
  {
    _id: '5c8ea07c496f1d90dd04226b',
    index: 4,
    guid: 'be5db3d5-e9c7-4d2f-9a1b-03fb25dede0c',
    featuredImage: 'http://placehold.it/640x640',
    pictures: [
      'http://placehold.it/32x32',
      'http://placehold.it/32x32',
      'http://placehold.it/32x32',
      'http://placehold.it/32x32',
    ],
    name: 'Chase Bradley',
    region: 'Wisconsin',
    company: 'PERKLE',
    email: 'chasebradley@perkle.com',
    phone: '+1 (864) 480-3874',
    address: '870 Kane Street, Sterling, Washington, 9564',
    about:
      'Sit voluptate mollit ad Lorem sit. Velit ipsum aliquip Lorem incididunt in ea elit culpa ut. Mollit eiusmod et ea proident. Culpa nulla duis ad est do labore exercitation proident aute in. Anim deserunt enim laboris excepteur deserunt. Ut aute fugiat do dolor. Elit nulla reprehenderit nulla Lorem excepteur amet.\r\n',
    useful:
      'Eiusmod adipisicing ea proident cupidatat excepteur id laborum. Ad eu aliqua nulla ex. Non est voluptate id dolor eiusmod amet. Anim aliquip fugiat sunt reprehenderit duis excepteur incididunt anim est commodo nostrud non proident. Quis sunt proident voluptate laboris laboris eu laboris veniam labore commodo. In velit sint ad ex in mollit dolor nulla est enim ullamco exercitation.\r\n',
    registered: '2015-01-30T02:58:23 -00:00',
    latitude: -27.435059,
    longitude: -70.56521,
    wines: [
      {
        name: 'voluptate eu veniam tempor',
        year: 2017,
        color: 'white',
        type: 'do non',
        price: 8,
      },
      {
        name: 'sint laborum Lorem est',
        year: 1996,
        color: 'white',
        type: 'aliquip culpa',
        price: 25,
      },
      {
        name: 'mollit tempor cillum ea',
        year: 2009,
        color: 'white',
        type: 'irure sit',
        price: 20,
      },
      {
        name: 'mollit deserunt sit elit',
        year: 1956,
        color: 'white',
        type: 'sunt aute',
        price: 8,
      },
      {
        name: 'eu dolor excepteur labore',
        year: 1969,
        color: 'red',
        type: 'ad tempor',
        price: 11,
      },
      {
        name: 'exercitation sunt nulla non',
        year: 2011,
        color: 'white',
        type: 'culpa deserunt',
        price: 14,
      },
    ],
    activities: [
      {
        title: 'eiusmod labore',
        type: 'tour',
        length: 1800000,
        size: 17,
        details:
          'Officia in elit qui elit. Nisi elit Lorem cillum excepteur adipisicing anim ex nisi dolor. Voluptate id non sint esse magna consequat id velit labore anim irure amet eiusmod. Laboris officia ut et tempor consequat excepteur velit incididunt qui incididunt dolor incididunt irure laborum. Id sit enim ad nostrud ex duis quis nostrud nostrud consectetur eiusmod sint veniam nostrud. Dolor elit adipisicing minim est est exercitation elit do aliqua ut deserunt ad. Nisi minim irure adipisicing quis tempor dolore.\r\n',
        price: 127,
      },
    ],
  },
  {
    _id: '5c8ea07c42db621e452b07f8',
    index: 5,
    guid: '6c59c5ca-8053-48da-9112-fd29a225764e',
    featuredImage: 'http://placehold.it/640x640',
    pictures: [
      'http://placehold.it/32x32',
      'http://placehold.it/32x32',
      'http://placehold.it/32x32',
      'http://placehold.it/32x32',
    ],
    name: 'Roy Richmond',
    region: 'Hawaii',
    company: 'FUTURIS',
    email: 'royrichmond@futuris.com',
    phone: '+1 (838) 448-3339',
    address: '362 Ocean Parkway, Logan, California, 9645',
    about:
      'Fugiat ex sit excepteur in aliqua quis. Et proident fugiat commodo dolor eu. Dolor pariatur elit magna minim aute anim minim ex irure consectetur. Officia enim dolor excepteur ullamco do elit mollit esse cupidatat fugiat excepteur cillum eiusmod.\r\n',
    useful:
      'Veniam eu sint incididunt elit sunt tempor magna. Voluptate dolore qui adipisicing duis aute commodo sunt do cillum cupidatat nisi duis. Magna ut non ea sint eiusmod.\r\n',
    registered: '2017-08-16T01:29:59 -01:00',
    latitude: -25.435059,
    longitude: -71.56521,
    wines: [
      {
        name: 'minim quis deserunt deserunt',
        year: 1980,
        color: 'white',
        type: 'deserunt ex',
        price: 8,
      },
      {
        name: 'eu aliqua nisi excepteur',
        year: 1974,
        color: 'white',
        type: 'sit ea',
        price: 5,
      },
      {
        name: 'aliqua officia cupidatat sint',
        year: 2001,
        color: 'red',
        type: 'incididunt sint',
      },
      {
        name: 'id cupidatat dolor ea',
        year: 1978,
        color: 'red',
        type: 'quis cupidatat',
        price: 18,
      },
      {
        name: 'excepteur in magna sint',
        year: 2010,
        color: 'red',
        type: 'ut cillum',
        price: 20,
      },
      {
        name: 'excepteur adipisicing magna quis',
        year: 1996,
        color: 'white',
        type: 'cillum consequat',
        price: 8,
      },
      {
        name: 'consequat sint in consequat',
        year: 1951,
        color: 'white',
        type: 'dolore ullamco',
        price: 8,
      },
    ],
    activities: [
      {
        title: 'velit cillum',
        type: 'tour',
        length: 1800000,
        size: 16,
        details:
          'Sint nisi magna incididunt excepteur elit. Do velit tempor occaecat eu id excepteur ad est exercitation. Lorem consequat magna elit qui dolor do aute mollit veniam veniam consequat id cillum id. Sint non proident aliquip ad dolor nulla duis pariatur cillum aliquip mollit proident voluptate. Quis ut proident Lorem incididunt occaecat. Minim aliquip amet tempor voluptate deserunt Lorem dolor sint laboris incididunt. Qui cillum laboris pariatur laboris nulla voluptate commodo eu non occaecat qui ad aliquip eu.\r\n',
        price: 161,
      },
    ],
  },
];
